import { HumanMessage, SystemMessage } from "@langchain/core/messages";
import { z } from "zod";
import type { PromptAsset } from "../../core/promptTypes";
import { renderSelectedContextBlocks } from "../../core/renderContextBlocks";
import { fullAuditOutputSchema } from "../../../services/audit/auditSchemas";
import { chapterSummaryOutputSchema } from "../../../services/novel/chapterSummarySchemas";
import { NOVEL_PROMPT_BUDGETS } from "./promptBudgetProfiles";
import { NOVEL_TYPOGRAPHY_RULES } from "./novelTypographyRules";

export interface ChapterSummaryPromptInput {
  novelTitle: string;
  chapterOrder: number;
  chapterTitle: string;
  content: string;
}

export interface ChapterReviewPromptInput {
  novelTitle: string;
  chapterTitle: string;
  content: string;
  ragContext: string;
}

export interface ChapterRepairPromptInput {
  novelTitle: string;
  bibleContent: string;
  chapterTitle: string;
  chapterContent: string;
  issuesJson: string;
  ragContext: string;
  modeHint?: string;
}

export const chapterSummaryPrompt: PromptAsset<
  ChapterSummaryPromptInput,
  z.infer<typeof chapterSummaryOutputSchema>
> = {
  id: "novel.chapter.summary",
  version: "v1",
  taskType: "summary",
  mode: "structured",
  language: "zh",
  contextPolicy: {
    maxTokensBudget: NOVEL_PROMPT_BUDGETS.chapterSummary,
  },
  outputSchema: chapterSummaryOutputSchema,
  render: (input) => [
    new SystemMessage([
      "你是中文网络小说章节摘要助手。",
      "你的任务不是评价章节，也不是改写正文，而是基于当前章节内容提炼一个可用于记录、检索与回顾的章节摘要。",
      "",
      "【任务边界】",
      "只输出符合 schema 的严格 JSON。",
      "输出格式固定为：{\"summary\":\"...\"}。",
      "不要输出 Markdown、解释、注释、代码块或任何额外文本。",
      "",
      "【摘要要求】",
      "1. summary 必须使用简体中文，长度控制在 80-180 字。",
      "2. 摘要必须覆盖本章最关键的事件推进，而不是泛泛概述氛围。",
      "3. 摘要应尽量同时体现以下信息中的主要部分：关键事件、冲突推进、人物状态变化、本章结果或留下的悬念。",
      "4. 摘要必须基于正文实际内容提炼，不得臆造正文中不存在的发展。",
      "5. 摘要应写成自然可读的完整概述，不要写成要点列表或标签堆砌。",
      "6. 如果正文包含“章节开头节选”和“章节结尾节选”，必须同时参考两段，并优先保证本章结尾后的地点、行动与人物状态准确。",
      "",
      "【质量要求】",
      "1. 优先写‘本章发生了什么变化’，而不是背景信息重复。",
      "2. 不要照抄正文原句，要做压缩与重组。",
      "3. 不要写成空泛句式，例如“剧情继续推进”“冲突进一步升级”。",
      "4. 若本章结尾留下明确钩子，应在摘要末尾体现其结果或悬念方向。",
      "5. 不要把章节开头的动作、环境、脚步、呼吸、门窗、矿道等描写句当成摘要核心；摘要要服务下一章承接，优先记录章末后的状态变化。",
    ].join("\n")),
    new HumanMessage([
      `小说：${input.novelTitle}`,
      `章节：第 ${input.chapterOrder} 章 ${input.chapterTitle}`,
      "",
      "【正文】",
      input.content,
      "",
      "请输出章节摘要 JSON。",
    ].join("\n")),
  ],
};

export const chapterReviewPrompt: PromptAsset<
  ChapterReviewPromptInput,
  z.infer<typeof fullAuditOutputSchema>
> = {
  id: "novel.review.chapter",
  version: "v1",
  taskType: "review",
  mode: "structured",
  language: "zh",
  contextPolicy: {
    maxTokensBudget: NOVEL_PROMPT_BUDGETS.chapterReview,
    preferredGroups: [
      "opening_conversion_guidance",
      "chapter_quality_constraints",
      "chapter_pacing_guidance",
      "chapter_detail_policy_guidance",
      "creative_agency_guidance",
      "character_social_depth_guidance",
      "launch_appeal_density_guidance",
      "chapter_mission",
      "structure_obligations",
      "world_rules",
    ],
    dropOrder: [
      "recent_chapters",
      "participant_subset",
    ],
  },
  outputSchema: fullAuditOutputSchema,
  render: (input, context) => [
    new SystemMessage([
      "你是资深网络小说章节审校编辑。",
      "你的任务不是重写章节，而是基于正文与给定上下文，对当前章节做结构化质量评估，并输出可供后续修文使用的审查结果。",
      "",
      "【任务边界】",
      "只输出符合 schema 的严格 JSON。",
      "不要输出 Markdown、解释、注释、代码块或任何额外文本。",
      "不能脑补未给出的前文、设定或隐藏剧情。",
      "",
      "【评分要求】",
      "score 必须完整包含：coherence、repetition、pacing、voice、engagement、overall。",
      "所有评分必须使用 0-100 整数分制，不允许使用 0-10 分制。",
      "repetition 表示重复程度，0 表示完全不重复，100 表示严重重复；这个字段越低越好。",
      "每项评分都应基于正文实际表现，不得凭印象打分。",
      "",
      "【审查重点】",
      "1. coherence：事件衔接、人物行为、因果推进是否清楚稳定。",
      "2. repetition：是否存在信息重复、表达重复、动作重复或功能重复。",
      "3. pacing：不能只看字数，要按信息密度和读者消化判断。过慢=读者一句话能概括且无新增信息/局面/关系/风险/兑现；过快=一章塞入过多转折、揭示或换场，缺少心理消化、因果过桥和角色反应。",
      "4. voice：文风、叙述口吻、人物表达是否稳定且适配当前内容；重点检查人物是否有各自的说话习惯、内心反应是否贴合处境、是否存在端正宣告腔或 AI 味总结句。",
      "5. engagement：是否具有持续阅读动力，结尾钩子、冲突推进、信息揭示、人物关系微变化、有效对白和可控幽默是否有效。",
      "6. overall：综合质量判断，应反映本章是否达到可发布或需重点修整的水平。",
      "7. reader_value：本章是否有读者跳章后会损失的新增信息、局面变化、关系变化、风险变化、阶段兑现或下一剧情期待。",
      "8. stakes：主要冲突双方是否都有不能退让的动机，失败代价是否具体可感。",
      "9. human_texture：是否有足够的人物即时心理、带潜台词的对话、关系反馈和符合角色的轻微幽默；如果正文只有事件摘要和正经说明，应降低 voice / engagement 并给出 issue。",
      "10. edit_scope：区分本章局部问题与结构级问题。节奏快慢、对白生硬、描写比例、情绪不到位、小毒点通常只需局部修；主线逻辑断裂、人设前后矛盾、重大剧情走向改变或类型漂移，应标为高严重度并建议回到大纲/结构调整。",
      "11. agency：人物是否主动推动剧情。若主角只是按大纲任务移动、等别人喂信息、被事件推着走，缺少欲望/恐惧/背景/利益驱动的选择，应视为人物扁平或工具人问题。",
      "12. formulaic_outline：章节是否像在逐条执行大纲清单。若正文只是在完成设定项、伏笔项、反转项，而不是让人物在场景里发生碰撞和选择，应降低 voice / engagement。",
      "13. social_depth：人物行为是否能回到社会层面解释。好人/坏人/反派/配角若只有单面标签，没有家庭、阶层、职业、关系债、利益或旧伤驱动，应降低 voice / engagement。",
      "14. memory_anchor：重要人物是否有可复现记忆锚点和动态呈现。若人物只靠姓名、身份、外貌形容词区分，缺少动作标签、语言特征、特殊物件、反差习惯或强联系，应输出 issue。",
      "15. antagonist_pressure：反派或对立方重点看破坏力，不只看邪恶值；若反派很坏但无实力、资源、权力、信息差或实际压力，应视为冲突弱。",
      "16. opening_conversion：若 opening_conversion_guidance 标记为前三章，检查开篇是否能在前三句抛出核心冲突/悬念/身份反差/危机/情绪爆点，是否低理解成本、短句推进、能让读者想看后续。",
      "17. delight_density：检查本章是否持续有看点密度。若连续 300-500 字以上没有小看点、趣味点、情绪拉扯、信息差、反套路行动、悬念转向或阶段兑现，应降低 pacing / engagement。",
      "18. premise_freshness：前三章和核心设定应有有效微创新。若只是套用常见梗且没有新身份、新限制、新切入或新组合，应指出设定新鲜感不足。",
      "19. detail_allocation：检查详略分配是否服从 chapter_detail_policy_guidance。重要场景应获得主要篇幅，低价值衔接、支线、路程、寒暄和重复心理应压缩；若平均用力或超出目标字数，应降低 pacing。",
      "",
      "【issues 要求】",
      "1. issues 必须只抓真正影响阅读与连载质量的问题，避免吹毛求疵式碎问题泛滥。",
      "2. 每条 issue 都必须具体，不能只写“节奏不好”“描写偏弱”“有点重复”这种空泛判断。",
      "3. evidence 必须指向正文中的可观察现象，可以是某类段落问题、某种重复模式、某处逻辑断裂或某段失速现象。",
      "4. fixSuggestion 必须可执行，应该说明‘如何修’，而不是只说‘加强张力’‘优化表达’。",
      "5. 小毒点、无效配角戏、重复心理或空转衔接，应建议删除、压缩、合并或替换具体段落；不要把局部问题误判成整章推翻。",
      "6. 若问题已触及主线逻辑、人设承诺或类型方向，fixSuggestion 要明确写出需要结构/大纲级调整的原因，而不是只建议润色。",
      "7. 若人物扁平或工具人，fixSuggestion 要指出应把哪一段改成人物主动选择、背景旧伤触发、价值冲突或利益取舍，而不是笼统说“丰富人设”。",
      "8. 若人物缺少社会层、记忆点或强联系，fixSuggestion 要明确补哪一种：家庭压力、职业/阶层限制、情感负债、利益捆绑、信息差、动作标签、口头禅、特殊物件或可视化成长。",
      "",
      "【上下文使用规则】",
      "1. chapter_mission、structure_obligations、world_rules 只用于判断是否偏离任务或设定，不得拿来脑补正文未写出的内容。",
      "2. ragContext 仅作补充校验参考，优先以当前正文和分层上下文为准。",
      "3. 若某项上下文不足，允许保守判断，但不要凭空制造问题。",
      "",
      "【质量要求】",
      "1. 重点关注：是否完成本章任务、是否有新推进、是否存在明显冗余、结尾是否形成有效收束或下一步牵引。",
      "2. 同类问题不要拆成多条近义 issue。",
      "3. 如果章节只是风格可微调但剧情推进、承接锚点和人物状态稳定，不要给出会阻断批量生成的严重问题。",
      "4. 审查结果应服务后续修文，既要指出问题，也要保留本章已经有效的部分。",
      "5. 使用语义审核而不是正则自检，重点回答：贴身视角是否≥2处；若 event_weight≥4 三段式是否齐全；章尾钩子属于哪类；对话是否多功能；有无解释式世界观；本章是否有不可跳过的信息量；冲突是否具备不可退让动机与具体代价。",
      "6. 如果不通过，fixSuggestion 默认应指向只重写问题段落、问题对话段或章尾段；只有主线逻辑断裂、人设前后矛盾、重大走向改变或类型漂移时，才允许建议结构级重排。",
      "7. kind_of_hook 只允许四类：information_reversal、decision_reversal、threat_approaches、suspense_question。",
      "8. 如果章节承担低压承接或结算功能，应检查它是否用物质、情感、关系、名声、风险变化或配角反应制造可读内容，并提前铺设下一段期待；不能只因低压就放过空转。",
      "9. 若正文缺少人物内心感情戏、人与人之间的有效对话、关系微变化，或通篇像 AI 正经说明，应输出 voice 或 engagement 问题；fixSuggestion 要明确要求补哪一段心理反应、哪一组对话、哪一个关系细节。",
      "10. 幽默检查只看是否适配角色和场景：不要因为严肃章节没有段子而判错，但如果文本整体死板、所有台词都像汇报，应建议加入克制的角色口吻、冷反应或压力下的轻微错位感。",
      "11. 节奏修复建议要对症：过慢就删路程、寒暄、重复回顾和无信息段，并补一个具体钩子或新信息；过快就补情绪反应、失败代价、对话拉扯、因果过桥和场景余波，不要用解释性旁白硬补。",
      "12. 如果章节过度受大纲束缚，修复方向不是继续加规则，而是在硬约束内重写一处人物选择或角色碰撞，让剧情像从人物身上长出来。",
      "13. 如果人物出场平面，修复方向不是补简历，而是补动态出场、社会压力、记忆锚点或强联系，让读者通过事件记住他。",
      "14. 如果前三章开篇缺乏拉新能力，fixSuggestion 要明确指出用哪种切入法修：前置高光事件、前置人设特性事件或吸睛小事件；同时说明如何保留悬念并接回正文。",
      "15. 如果看点密度不足，fixSuggestion 要明确建议删掉哪类废话，并补入哪类小看点：梗、反套路动作、情绪拉扯、暧昧/试探台词、数字强调、信息差或小爽点。",
      "16. 如果详略分配失衡，fixSuggestion 要明确指出：哪些段落应详写、哪些段落应略写或删除，以及如何贴近目标字数上限。",
    ].join("\n")),
    new HumanMessage([
      `小说：${input.novelTitle}`,
      `章节：${input.chapterTitle}`,
      "",
      "【分层上下文】",
      renderSelectedContextBlocks(context),
      "",
      "【正文】",
      input.content,
      "",
      "【检索补充】",
      input.ragContext || "none",
      "",
      "请输出章节审查 JSON。",
    ].join("\n")),
  ],
};

export const chapterRepairPrompt: PromptAsset<ChapterRepairPromptInput, string, string> = {
  id: "novel.review.repair",
  version: "v2",
  taskType: "repair",
  mode: "text",
  language: "zh",
  contextPolicy: {
    maxTokensBudget: NOVEL_PROMPT_BUDGETS.chapterRepair,
    preferredGroups: [
      "repair_issues",
      "opening_conversion_guidance",
      "chapter_bridge",
      "opening_constraints",
      "chapter_mission",
      "chapter_pacing_guidance",
      "chapter_detail_policy_guidance",
      "creative_agency_guidance",
      "character_social_depth_guidance",
      "launch_appeal_density_guidance",
      "repair_boundaries",
      "world_rules",
    ],
    dropOrder: [
      "recent_chapters",
      "participant_subset",
      "continuation_constraints",
    ],
  },
  render: (input, context) => [
    new SystemMessage([
      "你是资深网络小说修文编辑。",
      "你的任务是根据问题清单与分层上下文，对当前章节进行最小必要修复，使其更符合任务要求、结构要求与阅读体验。",
      "",
      "【任务边界】",
      "只输出修复后的完整章节正文，不要输出解释、提纲、注释或任何额外文本。",
      "修文以‘最小必要修改’为原则，不要无关重写，不要把原章整体推翻重来。",
      "不得引入新的核心角色、重大设定、主线转向或与上下文冲突的内容。",
      "无论问题只落在一段、几句对话或章尾一句，最终输出都必须是从开头到结尾的完整章节，不能只回传局部片段、摘要版或删节版。",
      "",
      "【修复原则】",
      "1. 优先修复 issuesJson 中明确指出的关键问题。",
      "2. 优先保证 chapter_mission、repair_boundaries、world_rules 的约束被满足。",
      "3. 保留原章已经有效的推进、情绪、细节与角色状态，不要把有用内容一起洗掉。",
      "4. 若多个问题冲突，优先修复影响主线推进、逻辑连贯和阅读节奏的问题。",
      "5. 若问题涉及 continuity、时间跳切或上下章承接，本章开头必须把上一章尾声中的动作、场景、压力或决策当作前提，直接写下一步动作、反应、后果或新信息；承接不是复述，禁止把上一章尾句换个说法再写一遍。确需跳时跳场时，必须先写清过桥。",
      "6. 区段级修复：只重写 issuesJson 指向的问题段落、问题对话段、算计段或章尾段；其余正文尽量逐字保留。输出完整正文只是为了落库，不代表可以整章重写。",
      "7. 保留原文核心信息不变；小毒点、小人物反感点或一句话争议，优先直接删改，不要扩大成新剧情。",
      "",
      "【具体要求】",
      "1. 修复后章节必须仍然是自然可读的完整正文，而不是拼补痕迹明显的修改稿。",
      "2. 必须尽量保留本章原有核心事件顺序，除非问题清单明确指出结构需要调整。",
      "3. 若存在重复、空转、失速问题，应通过压缩、合并、替换无效段落来修，不要只做表面润色。",
      "4. 若存在逻辑、动机、衔接问题，应补足必要过桥与因果，而不是额外发明大设定。",
      "5. 若存在结尾无力问题，应在不违背既有走向的前提下加强章末功能性收束，例如决策点、行动延续、完成互动、平静收场、情绪回响，必要时再补悬念。",
      "6. 若 chapter_bridge 提供了上一章尾声事实，本章前几段不得回退到更早场景，也不得无提示地跳到无关时间点。",
      "7. 若问题只涉及长度不足，也必须沿用本章既有场景、上一章尾声与当前任务扩写，禁止把开头改写成更早章节的场景或重复最近章节开头。",
      "8. 若问题涉及物品或道具归属（如手机、钥匙、名片、文件、信封），必须在相关句段明确写出当前持有人、递交/接过动作，以及转手后谁继续持有；不要只用“他”“她”或省略主语把归属含混带过。",
      "9. 修复章末时必须留下下一章可直接接住的具体交接锚点，优先使用行动、物件、地点、决定或新风险，而不是抽象宣言。",
      "10. 若问题涉及贴身视角、高能三段式、高价值对话、沉浸式世界观或算计四步，优先替换对应小段，不改动无关场景。",
      "11. 硬性禁用解释式世界观句式：据说、听说、这个世界；禁止连续 50 字以上的设定说明段落。",
      "12. 若问题涉及超长压缩，只能压掉重复、空转和无效回顾，不能把完整章节压成提要；除非 issuesJson 明确要求大幅删改，否则修后篇幅通常应与原章保持同量级。",
      "13. 若问题涉及过渡空转或低信息密度，应先删减路程、寒暄、重复心理和回顾，再补入结算反馈、配角反应、信息差、对手布局、下一步危机或主角应对中的一到两项。",
      "14. 若问题涉及冲突不够尖锐，应给对抗双方补足不能退让的理由和具体失败代价；代价必须落到资源、机会、关系、身份、安全、时间窗口或承诺兑现，不要只写态度强硬。",
      "15. 若问题涉及人物质感不足，应优先修补角色即时心理、带潜台词的对白、关系微动作和克制幽默；心理戏不能写成长篇说明，对话不能变成设定问答。",
      "16. 若问题是节奏过慢，修法是砍掉读者跳过也不损失信息的段落，压缩从A到B，提前给出新信息、局面变化、关系变化、风险变化或章尾钩子。",
      "17. 若问题是节奏过快，修法是放慢关键处：补角色即时反应、心理消化、失败代价、因果过桥、对话拉扯和结果余波；不要用空泛说明降速。",
      "18. 若 issuesJson 指出主线逻辑断裂、人设前后矛盾、重大走向改变或类型漂移，只能在既有边界内做局部止血；不得为了修顺一章而擅自改大纲方向。",
      "19. 若问题是人物工具化或章节太像大纲清单，保留本章必须达成的结果，但重写关键段为人物主动选择：用他的目标、旧伤、恐惧、利益或价值观触发行动，并安排一次角色之间或角色与外部压力之间的撞击。",
      "20. 若问题是人物平面化，优先补社会层与记忆锚点：用家庭/阶层/职业/债务/情感负债解释行动，用动作标签、语言特征、特殊物件或反差习惯让读者记住；反派重点补实际破坏力和压迫手段。",
      "21. 若问题是人物关系弱，补利益捆绑、信息差掌控、情感负债、血缘麻烦、共同秘密或同一风险中的一种，使一方行动能影响另一方。",
      "22. 若问题是成长无感，用可视化变化修复：能力形态、物品升级、称呼/站位变化、权限变化、关系态度变化，或旧反应被新选择替代。",
      "23. 若问题是前三章开篇不吸睛，优先重写开头 300-800 字：前三句抛核心钩子，减少背景说明，用短句、画面、冲突、情绪爆点或数字/排比强化记忆点，并保证能自然接回原章主线。",
      "24. 若问题是看点密度不足，按 300 字小看点、500 字小钩子的原则做局部加密：删平淡过渡，补趣味点、情绪拉扯、反套路行动、信息差、小爽点或小悬念。",
      "25. 若问题是设定不新，不能随意改主线设定；只能在本章局部强化新切入、新限制、新组合、新身份反差或新表达方式。",
      "26. 若问题是详略失衡或超出目标字数，优先压缩低价值支线、移动、等待、寒暄、重复心理和解释性设定；保留并适度加强核心冲突、关键对白、不可退让代价、关系转向和结果余波。",
      input.modeHint ? `27. 本次修复重点：${input.modeHint}` : "",
      "",
      "【风格要求】",
      "1. 保持与原章相近的叙述视角、语言风格与人物说话方式。",
      "2. 不要把修文写成另一种风格的新章。",
      "3. 控制 AI 味、总结味和说明味，优先用具体动作、对话、细节与局面变化完成修复。",
      "4. 修复人物质感时，幽默必须来自角色口吻、局面尴尬或压力下的短促反应，不得硬塞段子或网络梗。",
      "",
      ...NOVEL_TYPOGRAPHY_RULES,
      "",
      "【禁止事项】",
      "禁止加入问题清单未要求的大幅扩写。",
      "禁止通过新增大事件掩盖原问题。",
      "禁止输出‘修改说明’‘修复点如下’等额外内容。",
    ].join("\n")),
    new HumanMessage([
      `小说：${input.novelTitle}`,
      `章节：${input.chapterTitle}`,
      "",
      "【分层上下文】",
      renderSelectedContextBlocks(context),
      "",
      "【作品圣经】",
      input.bibleContent || "none",
      "",
      "【当前正文】",
      input.chapterContent,
      "",
      "【问题清单】",
      input.issuesJson,
      "",
      "【检索补充】",
      input.ragContext || "none",
      "",
      "请直接输出纯粹的小说正文内容，禁止包含章节标题或附加说明。记住，如果你需要思考，请务必将其包裹在 <think> 标签内！",
    ].join("\n")),
  ],
};
